### ISSUE TITLE
Exception: Sequence contains no elements

### ISSUE THREAD

**Issue by caino** [zblago/EF6TempTableKit#26]
Hello,
I'm using version 3.0.1 and when I try to use WithTempTableExpression extension with an IQueryable expression as a parameter i get the exception:

```
Sequence contains no elements
   in System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   in EF6TempTableKit.TableMetadataProvider.GetTableNameFromBaseType(Type baseType)
   in EF6TempTableKit.Extensions.DbContextExtensions.WithTempTableExpression[T](DbContext dbContexWithTempTable, IQueryable`1 expression, Boolean reuseExisting)
```

I'm sure passing an IQueryable containing data

**Comment by zblago** [comment]
Hi,

have you tried to compare with any of the unit tests within the project? Or else, can make some demo app where it breaks so that I can take a look into it.

Thanks.

**Comment by caino** [comment]
Hi,
Thank you for your answer, here you can find a demo application that replicates what I'm trying to do.

[TempTableTest.zip](https://github.com/zblago/EF6TempTableKit/files/12466441/TempTableTest.zip)

Thank you!

**Comment by zblago** [comment]
Hi, 

use DTO when doing projection. 
Instead of `var tempSourceQuery = ids.Select(i => new FilteringIntTempTable { Id = i, Guid = tmpGuid });`
do `var tempSourceQuery = ids.Select(i => new FilteringIntTempTableDto { Id = i, Guid = tmpGuid });`

Take a look into https://github.com/zblago/EF6TempTableKit, Getting Started 6th point. There you can see that I'm using 
`AddressTempTableDto`

Regards,
Zoran

**Comment by caino** [comment]
@zblago thank you, you made my day!

**Comment by caino** [comment]
@zblago thank you, you made my day!
